add fe pre-push

diff --git a/src/FE/.husky/pre-push b/src/FE/.husky/pre-push
--- a/src/FE/.husky/pre-push
+++ b/src/FE/.husky/pre-push
@@ -3,9 +3,10 @@
 
 if git diff --cached --name-only | grep '^src/FE/' >/dev/null; 
 then
-    cd src/FE
-    npm run format
+    if ! (cd src/FE && npm run build); then
+        echo "The front-end build failed."
+        exit 1
+    fi
 fi
 
 exit 0
-
